### ISSUE TITLE
Add listener when the activeClass props is triggered/changed via scrolling

### ISSUE THREAD

**Issue by Svartalheim** [toviszsolt/react-scrollspy#12]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem.
I had a problem where i had to use a listener when the activeClass is changed 

**Solutions**
I'd like to have the ScrollSpy have props to listen when the activeClass is triggered such as onActiveClassChange

**<ScrollSpy
          activeClass="active"
          onActiveClassChange={()=>{....}}
        > ...... </ScrollSpy>**
        
I know the lib is already providing with onClick handler, but if i'm only using that props my function wont run when the activeClass is changed via scrolling (not from clicking the nav item)

**Comment by toviszsolt** [comment]
@Svartalheim Thank you for your feedback.

The Intersection Handler function stores the id of the currently active anchor in a React State, so essentially it can be implement a function to trigger an event if the id (of the active anchor) changes. In short: we know when an element gets an activeClass, but not when it loses it.

Can you please explain the purpose of the use, so I can understand your perspective deeper?

**Comment by Svartalheim** [comment]
@toviszsolt 

So what i'm gonna do in my project is to keep the active element always on center of the viewport (like carousel), i have a trouble how to run the centering element function without knowing whether an element gets an activeClass or not.

You said there's a way to know when the activeClass can you give me example on how to using it?

**Comment by toviszsolt** [comment]
@Svartalheim 

Sorry, I wrote about internal functions.

If a function `onChangeActiveId` could be written with the currently active `id` and the previous active `id` in its arguments, would that solve your problem?

For example:
```jsx
<ScrollSpy
  onChangeActiveId={(activeId, previousId) => { /* Do something here based on ids */ }}
>
  {/* Children */}
</ScrollSpy>
```

**Comment by Svartalheim** [comment]
@toviszsolt 

Sure that'll works fine.

I only need the listener function, and the rest is nice to have i think.

**Comment by toviszsolt** [comment]
@Svartalheim 

New version (`2.0.6`) published https://www.npmjs.com/package/react-scrollspy-navigation
I hope that this will solve your problem.

Please be sure to report back.

**Comment by Svartalheim** [comment]
@toviszsolt Yeah, perfect!

Thank you so much for the update, i think we can close this issue.

**Comment by toviszsolt** [comment]
@Svartalheim 

You are very welcome, I am glad your problem has been solved.

If you found this project interesting, please consider supporting my open source work by [sponsoring me on GitHub](https://github.com/sponsors/toviszsolt) / [sponsoring me on PayPal](https://www.paypal.com/paypalme/toviszsolt) / [give the repo a star](https://github.com/toviszsolt/react-scrollspy).
