### ISSUE TITLE
Few bugs

### ISSUE THREAD

**Issue by pglejzer** [toviszsolt/react-scrollspy#2]
Hi, 

I used a little your library and found small bugs.

If props children are using 1 element (sometimes I need just 1 element in scrollspy) there is a problem to render this component. If the children's props have only 1 element is taking an object instead of an array. You can easily fix this or just add info to beware about that.

![image](https://user-images.githubusercontent.com/36240837/119015641-61fc6d80-b999-11eb-8337-7e471b2d3aae.png)

The second bug that I found is that if you are put some id to an element, this element has to have some width and height, if you don't add this class 'active' doesn't apply to the element in the scrollspy.

**Comment by pglejzer** [comment]
I made a small update with this children prop and added a small feature with nested elements with list #3 

@toviszsolt

**Comment by toviszsolt** [comment]
@pglejzer 
I so sorry for late answer, thank you very much for your feedback and works.
I will rewrite this component completely.
