### ISSUE TITLE
Add Support for Typescript

### ISSUE THREAD

**Issue by ghernandezr** [toviszsolt/react-scrollspy#5]
Currently, when I use this component in a React Vite Typescript project, I am getting this error:

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Thanks!!!!

**Comment by toviszsolt** [comment]
@ghernandezr
First of all, thanks for feedback.
Could you please make a sample stack on [CodeSandbox ](https://codesandbox.io/)or [StackBlitz](https://stackblitz.com/)?
It's a little hard to do anything if I don't see what's wrong...

**Comment by toviszsolt** [comment]
@ghernandezr 
Here is my sample stack -> [https://codesandbox.io/s/mvzn2](https://codesandbox.io/s/mvzn2)
You can fork and change it.

**Comment by toviszsolt** [comment]
@ghernandezr 
Now I found some info on -> https://stackoverflow.com/questions/34130539/uncaught-error-invariant-violation-element-type-is-invalid-expected-a-string

Please check how you import the component. Maybe you tried import the component as object.
The **correct** way to import -> `import ScrollSpy from 'react-scrollspy-navigation';`
The **bad** way to import -> `import { ScrollSpy } from 'react-scrollspy-navigation';`

**Comment by ghernandezr** [comment]
Hello @toviszsolt, sorry I do not reply sooner. Yes, I am using this method:

The correct way to import -> import ScrollSpy from 'react-scrollspy-navigation';

My problem was that I am using Typescript in my project and when I import ScrollSpy, the compiler complain because the types declaration for this library was not found. I made my declaration types and maybe that was the problem. I do that in the wrong way I think. When I execute the project in dev mode all work fine but when I compile for production the error is thrown. Do you plan to add support for typescript?

Thanks for the fast response.

Best Regards

**Comment by toviszsolt** [comment]
@ghernandezr you can add allowJs option to your tsconfig file. So this will solve your problem with all of available non-typescript packages.

Reference:
https://www.typescriptlang.org/tsconfig#JavaScript_Support_6247
