### ISSUE TITLE
Not working alongside scroll-snap

### ISSUE THREAD

**Issue by ryanregis** [toviszsolt/react-scrollspy#7]
When I click the links, the window doesn't scroll when scroll-snap in CSS is enabled. Is this a feature or just wasn't included?

**Comment by toviszsolt** [comment]
@ryanregis scroll-snap is a browser built-in feature. Unfortunately, browser built-in features are breaking the developer code by taking complete control over scroll events and overriding them. Now you have to decide which feature gives you a better user experience and use it.
