### ISSUE TITLE
my nextjs 

### ISSUE THREAD

**Issue by pengxinseo** [toviszsolt/react-scrollspy#9]
How to use my nextjs project? It seems like I didn't understand after reading the instructions. Can you provide a tutorial on how to use nextjs

**Comment by toviszsolt** [comment]
@pengxinseo sure, I'm glad to help, can you please show me some code? Or at least try to describe how the page is structured and where you want to apply ScrollSpy, so I know what you want.

**Comment by pengxinseo** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zsolt ***@***.***&gt;; 
发送时间: 2024年4月19日(星期五) 晚上9:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [toviszsolt/react-scrollspy] my nextjs  (Issue #9)














 
@pengxinseo sure, I'm glad to help, can you please show me some code? Or at least try to describe how the page is structured and where you want to apply ScrollSpy, so I know what you want.

**Comment by toviszsolt** [comment]
We solved this on Telegram.
If you have any other issue please create a new ticket.
